source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CoinDuel' do
    pod 'Alamofire', '~> 4.6'
	pod 'SwiftyJSON'
	pod 'Charts'
	pod 'FeedbackEffect'
	pod 'NVActivityIndicatorView'
	pod 'OneSignal', '>= 2.5.2', '< 3.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
